name: Trigger auto deployment for album-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/album-api-AutoDeployTrigger-42e0f0ee-862a-4594-82ee-ab6e46d3cfa5.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ALBUMAPI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/src 
          registryUrl: ca911149b1b2acr.azurecr.io
          registryUsername: ${{ secrets.ALBUMAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ALBUMAPI_REGISTRY_PASSWORD }}
          containerAppName: album-api
          resourceGroup: album-containerapps
          imageToBuild: ca911149b1b2acr.azurecr.io/album-api:${{ github.sha }}
          dockerfilePath: Dockerfile

     

